import mido
# MIDIファイルを準備 --- (※1)
midi = mido.MidiFile()
track = mido.MidiTrack()
midi.tracks.append(track)
# トラックにノート(発音)を追加 --- (※2)
track.append(mido.Message('note_on', note=60, time=0))
track.append(mido.Message('note_off', note=60, time=480))
track.append(mido.Message('note_on', note=62, time=0))
track.append(mido.Message('note_off', note=62, time=480))
track.append(mido.Message('note_on', note=64, time=0))
track.append(mido.Message('note_off', note=64, time=480))
# MIDIファイルを保存 --- (※3)
midi.save('test.mid')
